# Generated by Django 4.2.5 on 2023-09-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('page', models.SmallIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
